config/routes.rb
Rails.application.routes.draw do
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # # Index restaurants
  # get '/restaurants', to: 'restaurants#index'
  # # Show restaurant
  # get '/restaurants/:id', to: 'restaurants#show', as: :restaurant
  # # Create restaurant
  # get '/restaurants/new', to: 'restaurants#new'
  # post '/restaurants/', to: 'restaurants#create'
  # # Add review to restaurant
  # get 'restaurants/'
  resources :restaurants, only: [:index, :new, :create, :show, :destroy] do
    resources :reviews, only:[:new, :create]
  end
  resources :reviews, only:[:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, presence: true, inclusion: { in: ['chinese', 'italian', 'japanese', 'french', 'belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: (0..5) }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, except: :destroy

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant.id)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>
<% end %>

app/views/restaurants/new.html.erb
<h2>New restaurant</h2>
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.label :category %>
  <%= f.select :category, ['chinese', 'italian', 'japanese', 'french', 'belgian'] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p>Category: <%= @restaurant.category %></p>
<p>Address: <%= @restaurant.address %></p>
<p>Phone number: <%= @restaurant.phone_number %></p>

<%# <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
<%= link_to 'Back', restaurants_path %>
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>
<%= link_to "Delete #{@restaurant.name}", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %>

<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">
      <p><%= "⭐️" * review.rating  %></p>
      <p><%= review.content %></p>
      <%= link_to 'Delete review', review_path(review.id), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h2>Add a review</h2>
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :rating %>
  <%= f.select :rating, (0..5) %>
  <%= f.submit %>
<% end %>